### ISSUE TITLE
Nil Pointer issues when using Sampling

### ISSUE THREAD

**Issue by rclayton-godaddy** [elastic/apm-agent-go#1324]
**Describe the bug**

When we set the environment variable `ELASTIC_APM_TRANSACTION_SAMPLE_RATE` to any other value than `1.0` our server crashes from a seg fault because `Span` is `nil`.

**To Reproduce**
1. Set `ELASTIC_APM_TRANSACTION_SAMPLE_RATE=0.1`
2. Execute request that uses tracing:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x464e051]

goroutine 630 [running]:
go.elastic.co/apm/v2.(*Span).End(0x0)
        /Users/rclayton/go/pkg/mod/go.elastic.co/apm/v2@v2.1.0/span.go:336 +0x31
go.elastic.co/apm/module/apmawssdkgo/v2.send(0xc003eb8000)
        /Users/rclayton/go/pkg/mod/go.elastic.co/apm/module/apmawssdkgo/v2@v2.1.0/session.go:165 +0x485
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc003eb8228, 0xc003eb8000)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/handlers.go:267 +0xca
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc003eb8000)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:602 +0x12e
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc003eb8000)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:555 +0x252
github.com/aws/aws-sdk-go/service/dynamodb.(*DynamoDB).QueryWithContext(0xc000324e30, {0x5499770, 0xc0007cad80}, 0xc003de32c0, {0x0, 0x0, 0x0})
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/service/dynamodb/api.go:5027 +0xe9
github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func1(0xc003de32c0)
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:735 +0xcb
github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func2(0xc003de32c0)
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:772 +0xd7
created by github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:767 +0x306
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x464e051]

goroutine 628 [running]:
go.elastic.co/apm/v2.(*Span).End(0x0)
        /Users/rclayton/go/pkg/mod/go.elastic.co/apm/v2@v2.1.0/span.go:336 +0x31
go.elastic.co/apm/module/apmawssdkgo/v2.send(0xc003e0a500)
        /Users/rclayton/go/pkg/mod/go.elastic.co/apm/module/apmawssdkgo/v2@v2.1.0/session.go:165 +0x485
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc003e0a728, 0xc003e0a500)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/handlers.go:267 +0xca
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc003e0a500)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:602 +0x12e
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc003e0a500)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:555 +0x252
github.com/aws/aws-sdk-go/service/dynamodb.(*DynamoDB).QueryWithContext(0xc000324e30, {0x5499770, 0xc0007cad80}, 0xc003de3040, {0x0, 0x0, 0x0})
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/service/dynamodb/api.go:5027 +0xe9
github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func1(0xc003de3040)
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:735 +0xcb
github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func2(0xc003de3040)
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:772 +0xd7
created by github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:767 +0x306
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x464e051]

goroutine 629 [running]:
go.elastic.co/apm/v2.(*Span).End(0x0)
        /Users/rclayton/go/pkg/mod/go.elastic.co/apm/v2@v2.1.0/span.go:336 +0x31
go.elastic.co/apm/module/apmawssdkgo/v2.send(0xc000241400)
        /Users/rclayton/go/pkg/mod/go.elastic.co/apm/module/apmawssdkgo/v2@v2.1.0/session.go:165 +0x485
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc000241628, 0xc000241400)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/handlers.go:267 +0xca
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc000241400)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:602 +0x12e
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc000241400)
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:555 +0x252
github.com/aws/aws-sdk-go/service/dynamodb.(*DynamoDB).QueryWithContext(0xc000324e30, {0x5499770, 0xc0007cad80}, 0xc003de3180, {0x0, 0x0, 0x0})
        /Users/rclayton/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/service/dynamodb/api.go:5027 +0xe9
github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func1(0xc003de3180)
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:735 +0xcb
github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func2(0xc003de3180)
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:772 +0xd7
created by github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts
        /Users/rclayton/Development/GoDaddy/dc-customer-engagement/pkg/infrastructure/storage/dynamo/repository.go:767 +0x306
Exiting.
```

**Expected behavior**

I would expect an unsampled request to work like any other request, just not report the result at the end.

**Comment by axw** [comment]
@rclayton-godaddy I think you're hitting a bug that was fixed by https://github.com/elastic/apm-agent-go/pull/1273. That fix hasn't been released yet. We should have a new release going out in the next few weeks. In the mean time: can you please try updating to the latest commit on main, and see if that resolves the issue?

**Comment by rclayton-godaddy** [comment]
Thanks, will try it out tomorrow.

**Comment by rclayton-godaddy** [comment]
@axw @tbellerose-godaddy We updated the library to `master` and are seeing weird errors.  Instead of a `panic` crashing the server (and us getting a stack trace), we are getting quiet failures resulting in 500 errors on HTTP routes.  The worse part is that this client is somehow circumventing our error handling and responding 500 directly over the HTTP interface.  

For example, with this code: 
![image](https://user-images.githubusercontent.com/82417610/192607729-6e372dcb-a86a-4fd2-9def-2f459c528211.png)

`ls.GetAllEngagementSets` is invoked (and internally will call DynamoDB), but we never get the result (assume a panic somewhere in here, but it is being caught?).

This shows the output of the logs:
![image](https://user-images.githubusercontent.com/82417610/192608007-a241224e-b87b-4bf4-bf71-21aed424d30f.png)

**Comment by rclayton-godaddy** [comment]
OK, looks like we were able to get a stack trace from one of our servers:
```
goroutine 249 [running]:

go.elastic.co/apm/v2.(*Span).End(0x0)

/go/pkg/mod/go.elastic.co/apm/v2@v2.1.1-0.20220927070739-b4e40b3cc565/span.go:361 +0x45

go.elastic.co/apm/module/apmawssdkgo/v2.send(0xc00280ea00)

/go/pkg/mod/go.elastic.co/apm/module/apmawssdkgo/v2@v2.1.0/session.go:165 +0x4d6

github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc00280ec28, 0xc00280ea00)

/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/handlers.go:267 +0x9a

github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc00280ea00)

/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:602 +0xbf

github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc00280ea00)

/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/aws/request/request.go:555 +0x156

github.com/aws/aws-sdk-go/service/dynamodb.(*DynamoDB).QueryWithContext(0x203000?, {0x14d1a18, 0xc002802b70}, 0x7?, {0x0, 0x0, 0x203000?})

/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.86/service/dynamodb/api.go:5027 +0x186

github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func1(0xc002802d80?)

/app/pkg/infrastructure/storage/dynamo/repository.go:735 +0x66

github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts.func2(0xffffffffffffffff?)

/app/pkg/infrastructure/storage/dynamo/repository.go:772 +0xa5

created by github.com/gdcorp-digitalcare/dc-customer-engagement/pkg/infrastructure/storage/dynamo.(*storage).getFacts

/app/pkg/infrastructure/storage/dynamo/repository.go:767 +0x11d
```

**Comment by axw** [comment]
@rclayton-godaddy from the stack trace, it looks like you may have updated the `go.elastic.co/apm/v2` module to main (has the suffix "@v2.1.1-0.20220927070739-b4e40b3cc565"), but not `go.elastic.co/module/apmawssdkgo/v2` (has the suffix "@v2.1.0"). Can you check that please?

**Comment by tbellerose-godaddy** [comment]
@axw My bad, didn't notice that the aws sdk was a separate module when updating. After updating that, it appears to have resolved our issue. Thanks!

**Comment by axw** [comment]
No worries, thanks for confirming that it's fixed @tbellerose-godaddy. Please keep an eye out for a new release, it shouldn't be too far away.

**Comment by roffe** [comment]
Just ran into this as well when deploying an application with to prod that had lower sampling rate than what we had been trying in staging. `@v2.1.1-0.20220927070739-b4e40b3cc565` solved the problem

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac61c5]

goroutine 91 [running]:
go.elastic.co/apm/v2.(*Span).End(0x0)
        /home/roffe/go/pkg/mod/go.elastic.co/apm/v2@v2.1.0/span.go:336 +0x45
go.elastic.co/apm/module/apmawssdkgo/v2.send(0xc00026f400)
        /home/roffe/go/pkg/mod/go.elastic.co/apm/module/apmawssdkgo/v2@v2.1.0/session.go:165 +0x4d6
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc00026f628, 0xc00026f400)
        /home/roffe/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.115/aws/request/handlers.go:267 +0x9a
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc00026f400)
        /home/roffe/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.115/aws/request/request.go:602 +0xbf
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc00026f400)
        /home/roffe/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.115/aws/request/request.go:555 +0x156
github.com/aws/aws-sdk-go/service/s3.(*S3).HeadObjectWithContext(0xc0009627e0?, {0x146fb90, 0xc000469a00}, 0x112ceca?, {0x0, 0x0, 0x146fb90?})
        /home/roffe/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.115/service/s3/api.go:5706 +0x186
github.com/tjek/picasso/pkg/source.(*S3ImageSource).Get(0xc0009960c0, 0xc00082f200)
...
```
