### ISSUE TITLE
ci: SIGABRT: abort while running on MacOS with Go 1.15

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-go#1350]
```
=== RUN   TestTracerSetConfigWatcher
objc[23746]: Attempt to use unknown class 0x7ff85b814018.
SIGABRT: abort
PC=0x7ff81a0dadba m=3 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7ff81a0dadba
stack: frame={sp:0x700004d62e38, fp:0x0} stack=[0x700004ce4[350](https://github.com/elastic/apm-agent-go/actions/runs/3462410362/jobs/5781263453#step:5:351),0x700004d63f50)
0000700004d62d38:  0000000000000002  0000000000000002 
0000700004d62d48:  0000000005b64000  0000000005b64400 
0000700004d62d58:  0000000000000001  0000700004d62dc0 
0000700004d62d68:  00007ff819f0f677  e27917cc0412a3a4 
0000700004d62d78:  f691000840001001  e27917cc0412ffff 
0000700004d62d88:  0000000000000030  0000000000000000 
0000700004d62d98:  000000000000002d  000000000000002d 
0000700004d62da8:  0000600003304000  0000000005b64000 
0000700004d62db8:  00007ff85b827000  0000700004d62df0 
0000700004d62dc8:  00007ff819f0f5a4  00007ff819f0f56c 
0000700004d62dd8:  000000000000002d  0000000000000001 
0000700004d62de8:  00007ff85b827000  0000700004d62e30 
0000700004d62df8:  00007ff819f2babb  000000000000002c 
0000700004d62e08:  000000000000002d  0000600003304000 
0000700004d62e18:  0000600003304000  0000600002c00000 
0000700004d62e28:  0000000000000000  0000700004d62e60 
0000700004d62e38: <00007ff81a0dc877  0000000000000000 
0000700004d62e48:  0000002004d62ea0  0000600002c00000 
0000700004d62e58:  0000700004d62ea0  0000600003304000 
0000700004d62e68:  0000600003304000  0000000000000080 
0000700004d62e78:  0000000000000001  0000700004d62e90 
0000700004d62e88:  00007ff81a0dc827  0000700004d62ed0 
0000700004d62e98:  00007ff819fa7bf6  0000600002c00080 
0000700004d62ea8:  0000000000000000  0000600002c00000 
0000700004d62eb8:  00007ffffffffff8  000000000000000b 
0000700004d62ec8:  00007ff85b814018  0000700004d62fb0 
0000700004d62ed8:  00007ff819fa7b84  0000000000000000 
0000700004d62ee8:  00007ff85b814018  0000000000000001 
0000700004d62ef8:  0000000000000001  00000000ffffffff 
0000700004d62f08:  0000000000000000  0000000000000000 
0000700004d62f18:  0000000000000000  0000000000000000 
0000700004d62f28:  0000000000000000  0000000000000000 
runtime: unknown pc 0x7ff81a0dadba
stack: frame={sp:0x700004d62e38, fp:0x0} stack=[0x700004ce4350,0x700004d63f50)
0000700004d62d38:  0000000000000002  0000000000000002 
0000700004d62d48:  0000000005b64000  0000000005b64400 
0000700004d62d58:  0000000000000001  0000700004d62dc0 
0000700004d62d68:  00007ff819f0f677  e27917cc0412a3a4 
0000700004d62d78:  f691000840001001  e27917cc0412ffff 
0000700004d62d88:  0000000000000030  0000000000000000 
0000700004d62d98:  000000000000002d  000000000000002d 
0000700004d62da8:  0000600003304000  0000000005b64000 
0000700004d62db8:  00007ff85b827000  0000700004d62df0 
0000700004d62dc8:  00007ff819f0f5a4  00007ff819f0f56c 
0000700004d62dd8:  000000000000002d  0000000000000001 
0000700004d62de8:  00007ff85b827000  0000700004d62e30 
0000700004d62df8:  00007ff819f2babb  000000000000002c 
0000700004d62e08:  000000000000002d  0000600003304000 

goroutine 19 [select]:
go.elastic.co/apm/v2.(*Tracer).loop(0xc000125ba0)
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:1019 +0x1434
created by go.elastic.co/apm/v2.newTracer
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:540 +0x17bf

goroutine 34 [chan receive]:
go.elastic.co/apm/v2.(*Tracer).loop.func2(0xc0000a00c0, 0xc0000a0060, 0x4c0f260, 0xc000096000, 0xc00009c0c0, 0xc000125ba0, 0xc00009e000)
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:912 +0x2e5
created by go.elastic.co/apm/v2.(*Tracer).loop
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:909 +0x570

goroutine 324 [chan send]:
go.elastic.co/apm/v2.newTracer(0xc00061af78, 0x8, 0x0, 0x0, 0x0, 0x0, 0x4c01520, 0xc002f7e750, 0x2540be400, 0x6fc23ac00, ...)
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:556 +0x196a
go.elastic.co/apm/v2.NewTracerOptions(0xc00061af78, 0x8, 0x0, 0x0, 0x0, 0x0, 0x4c01520, 0xc002f7e750, 0x2540be400, 0x6fc23ac00, ...)
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:446 +0xf8
go.elastic.co/apm/v2.NewTracer(...)
	/Users/runner/work/apm-agent-go/apm-agent-go/tracer.go:433
go.elastic.co/apm/v2_test.TestTracerSetConfigWatcher(0xc002fa8300)
	/Users/runner/work/apm-agent-go/apm-agent-go/config_test.go:325 +0x145
testing.tRunner(0xc002fa8300, 0x4b2a880)
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/testing/testing.go:1168 +0x5bc

goroutine 303 [select]:
net.cgoLookupIP(0x4c0f260, 0xc003000c40, 0x4af436a, 0x3, 0xc003018720, 0x9, 0xf8, 0x5b807d0, 0x88, 0xc00301b200, ...)
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/net/cgo_unix.go:229 +0x1e9
net.(*Resolver).lookupIP(0x4fce640, 0x4c0f260, 0xc003000c40, 0x4af436a, 0x3, 0xc003018720, 0x9, 0x4a38160, 0xc001b81bc0, 0xc0000b7d78, ...)
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/net/lookup_unix.go:96 +0x217
net.glob..func1(0x4c0f260, 0xc003000c40, 0xc000616f00, 0x4af436a, 0x3, 0xc003018720, 0x9, 0xc0000b7ec0, 0xc028aaa8e8, 0x10[352](https://github.com/elastic/apm-agent-go/actions/runs/3462410362/jobs/5781263453#step:5:353)cd19, ...)
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/net/hook.go:23 +0x9f
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/net/lookup.go:293 +0x162
internal/singleflight.(*Group).doCall(0x4fce650, 0xc0005dcf50, 0xc003018730, 0xd, 0xc003000c80)
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/internal/singleflight/singleflight.go:95 +0x52
created by internal/singleflight.(*Group).DoChan
	/Users/runner/hostedtoolcache/go/1.15.10/x64/src/internal/singleflight/singleflight.go:88 +0x4be
```

Further details in the logs:
- https://github.com/elastic/apm-agent-go/actions/runs/3462410362/jobs/5781263453

**Comment by v1v** [comment]
I tried with the latest golang 1.15 version with the same outcome
