### ISSUE TITLE
Investigate CI failure

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#725]
Investigate this alarming fatal error in CI: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/master/121/pipeline/#step-245-log-1565

> [2020-02-26T13:01:22.340Z] === RUN   TestContainerFilterUnknownRoute
> [2020-02-26T13:01:22.340Z] runtime: pointer 0xc000451d40 to unused region of span span.base()=0xc0001d4000 span.limit=0xc0001d9e80 span.state=1
> [2020-02-26T13:01:22.340Z] runtime: found in object at *(0xc0000e70e0+0x28)
> [2020-02-26T13:01:22.340Z] object=0xc0000e70e0 s.base()=0xc0000e6000 s.limit=0xc0000e7fe0 s.spanclass=22 s.elemsize=160 s.state=mSpanInUse
> [2020-02-26T13:01:22.340Z]  *(object+0) = 0x1010100000050
> [2020-02-26T13:01:22.340Z]  *(object+8) = 0xc0004517f0
> [2020-02-26T13:01:22.340Z]  *(object+16) = 0x85ddf3
> [2020-02-26T13:01:22.340Z]  *(object+24) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+32) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+40) = 0xc000451d40 <==
> [2020-02-26T13:01:22.340Z]  *(object+48) = 0x9fec7c
> [2020-02-26T13:01:22.340Z]  *(object+56) = 0xc000451928
> [2020-02-26T13:01:22.340Z]  *(object+64) = 0x85dbf7
> [2020-02-26T13:01:22.340Z]  *(object+72) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+80) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+88) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+96) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+104) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+112) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+120) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+128) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+136) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+144) = 0x0
> [2020-02-26T13:01:22.340Z]  *(object+152) = 0x0
> [2020-02-26T13:01:22.340Z] fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
> [2020-02-26T13:01:22.340Z] 
> [2020-02-26T13:01:22.340Z] runtime stack:
> [2020-02-26T13:01:22.340Z] runtime.throw(0x9c9fa2, 0x3e)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0x7ffe54e01a28 sp=0x7ffe54e019f8 pc=0x436012
> [2020-02-26T13:01:22.340Z] runtime.badPointer(0x7fcfb69c0878, 0xc000451d40, 0xc0000e70e0, 0x28)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/mbitmap.go:380 +0x230 fp=0x7ffe54e01a70 sp=0x7ffe54e01a28 pc=0x4161e0
> [2020-02-26T13:01:22.340Z] runtime.findObject(0xc000451d40, 0xc0000e70e0, 0x28, 0x7fcfb69bfbb8, 0xc000034698, 0x0)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/mbitmap.go:416 +0x9b fp=0x7ffe54e01aa8 sp=0x7ffe54e01a70 pc=0x41628b
> [2020-02-26T13:01:22.340Z] runtime.scanobject(0xc0000e70e0, 0xc000034698)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/mgcmark.go:1274 +0x235 fp=0x7ffe54e01b38 sp=0x7ffe54e01aa8 pc=0x421325
> [2020-02-26T13:01:22.340Z] runtime.gcDrain(0xc000034698, 0x7)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/mgcmark.go:1032 +0x1fb fp=0x7ffe54e01b90 sp=0x7ffe54e01b38 pc=0x420b2b
> [2020-02-26T13:01:22.340Z] runtime.gcBgMarkWorker.func2()
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/mgc.go:1955 +0x169 fp=0x7ffe54e01bd0 sp=0x7ffe54e01b90 pc=0x462de9
> [2020-02-26T13:01:22.340Z] runtime.systemstack(0x465a04)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66 fp=0x7ffe54e01bd8 sp=0x7ffe54e01bd0 pc=0x465b76
> [2020-02-26T13:01:22.340Z] runtime.mstart()
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/proc.go:1041 fp=0x7ffe54e01be0 sp=0x7ffe54e01bd8 pc=0x43adf0
> [2020-02-26T13:01:22.340Z] 
> [2020-02-26T13:01:22.340Z] goroutine 21 [GC worker (idle)]:
> [2020-02-26T13:01:22.340Z] runtime.systemstack_switch()
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc000038f60 sp=0xc000038f58 pc=0x465b00
> [2020-02-26T13:01:22.340Z] runtime.gcBgMarkWorker(0xc000033000)
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/mgc.go:1919 +0x1be fp=0xc000038fd8 sp=0xc000038f60 pc=0x41dace
> [2020-02-26T13:01:22.340Z] runtime.goexit()
> [2020-02-26T13:01:22.340Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000038fe0 sp=0xc000038fd8 pc=0x467c11
> [2020-02-26T13:01:22.341Z] created by runtime.gcBgMarkStartWorkers
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/mgc.go:1813 +0x77
> [2020-02-26T13:01:22.341Z] 
> [2020-02-26T13:01:22.341Z] goroutine 1 [chan receive]:
> [2020-02-26T13:01:22.341Z] runtime.gopark(0x9d3350, 0xc000098238, 0xc0000f170e, 0x2)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc000421b38 sp=0xc000421b18 pc=0x438a40
> [2020-02-26T13:01:22.341Z] runtime.chanrecv(0xc0000981e0, 0xc000ac3c4f, 0xc000000101, 0x503017)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/chan.go:525 +0x2e7 fp=0xc000421bc8 sp=0xc000421b38 pc=0x4076a7
> [2020-02-26T13:01:22.341Z] runtime.chanrecv1(0xc0000981e0, 0xc000ac3c4f)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/chan.go:407 +0x2b fp=0xc000421bf8 sp=0xc000421bc8 pc=0x40736b
> [2020-02-26T13:01:22.341Z] testing.(*T).Run(0xc00011e7e0, 0x9bc48f, 0x1f, 0x9d2cb8, 0x48b001)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/testing/testing.go:1044 +0x37e fp=0xc000421ca8 sp=0xc000421bf8 pc=0x50303e
> [2020-02-26T13:01:22.341Z] testing.runTests.func1(0xc00011e5a0)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/testing/testing.go:1285 +0x78 fp=0xc000421cf8 sp=0xc000421ca8 pc=0x507268
> [2020-02-26T13:01:22.341Z] testing.tRunner(0xc00011e5a0, 0xc00027fdd8)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/testing/testing.go:992 +0xdc fp=0xc000421d48 sp=0xc000421cf8 pc=0x502c4c
> [2020-02-26T13:01:22.341Z] testing.runTests(0xc00000e0c0, 0xddf820, 0x5, 0x5, 0x0)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/testing/testing.go:1283 +0x2a7 fp=0xc000421e08 sp=0xc000421d48 pc=0x504637
> [2020-02-26T13:01:22.341Z] testing.(*M).Run(0xc000152980, 0x0)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/testing/testing.go:1200 +0x15f fp=0xc000421ee8 sp=0xc000421e08 pc=0x50349f
> [2020-02-26T13:01:22.341Z] main.main()
> [2020-02-26T13:01:22.341Z] 	_testmain.go:350 +0x1d4 fp=0xc000421f88 sp=0xc000421ee8 pc=0x8a7d04
> [2020-02-26T13:01:22.341Z] runtime.main()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:203 +0x212 fp=0xc000421fe0 sp=0xc000421f88 pc=0x438662
> [2020-02-26T13:01:22.341Z] runtime.goexit()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000421fe8 sp=0xc000421fe0 pc=0x467c11
> [2020-02-26T13:01:22.341Z] 
> [2020-02-26T13:01:22.341Z] goroutine 2 [force gc (idle)]:
> [2020-02-26T13:01:22.341Z] runtime.gopark(0x9d3540, 0xde6e20, 0x1411, 0x1)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc00003cfb0 sp=0xc00003cf90 pc=0x438a40
> [2020-02-26T13:01:22.341Z] runtime.goparkunlock(...)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:310
> [2020-02-26T13:01:22.341Z] runtime.forcegchelper()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:253 +0xb7 fp=0xc00003cfe0 sp=0xc00003cfb0 pc=0x4388f7
> [2020-02-26T13:01:22.341Z] runtime.goexit()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00003cfe8 sp=0xc00003cfe0 pc=0x467c11
> [2020-02-26T13:01:22.341Z] created by runtime.init.6
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:242 +0x35
> [2020-02-26T13:01:22.341Z] 
> [2020-02-26T13:01:22.341Z] goroutine 3 [GC sweep wait]:
> [2020-02-26T13:01:22.341Z] runtime.gopark(0x9d3540, 0xde7000, 0x140c, 0x1)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc00003d7a8 sp=0xc00003d788 pc=0x438a40
> [2020-02-26T13:01:22.341Z] runtime.goparkunlock(...)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:310
> [2020-02-26T13:01:22.341Z] runtime.bgsweep(0xc000064000)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/mgcsweep.go:89 +0x131 fp=0xc00003d7d8 sp=0xc00003d7a8 pc=0x424441
> [2020-02-26T13:01:22.341Z] runtime.goexit()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00003d7e0 sp=0xc00003d7d8 pc=0x467c11
> [2020-02-26T13:01:22.341Z] created by runtime.gcenable
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/mgc.go:214 +0x5c
> [2020-02-26T13:01:22.341Z] 
> [2020-02-26T13:01:22.341Z] goroutine 4 [GC scavenge wait]:
> [2020-02-26T13:01:22.341Z] runtime.gopark(0x9d3540, 0xde6fc0, 0x140d, 0x1)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc00003df78 sp=0xc00003df58 pc=0x438a40
> [2020-02-26T13:01:22.341Z] runtime.goparkunlock(...)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:310
> [2020-02-26T13:01:22.341Z] runtime.bgscavenge(0xc000064000)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/mgcscavenge.go:285 +0x20f fp=0xc00003dfd8 sp=0xc00003df78 pc=0x422aef
> [2020-02-26T13:01:22.341Z] runtime.goexit()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00003dfe0 sp=0xc00003dfd8 pc=0x467c11
> [2020-02-26T13:01:22.341Z] created by runtime.gcenable
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/mgc.go:215 +0x7e
> [2020-02-26T13:01:22.341Z] 
> [2020-02-26T13:01:22.341Z] goroutine 5 [finalizer wait]:
> [2020-02-26T13:01:22.341Z] runtime.gopark(0x9d3540, 0xe12228, 0x1410, 0x1)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc00003e758 sp=0xc00003e738 pc=0x438a40
> [2020-02-26T13:01:22.341Z] runtime.goparkunlock(...)
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/proc.go:310
> [2020-02-26T13:01:22.341Z] runtime.runfinq()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/mfinal.go:175 +0xa3 fp=0xc00003e7e0 sp=0xc00003e758 pc=0x41a063
> [2020-02-26T13:01:22.341Z] runtime.goexit()
> [2020-02-26T13:01:22.341Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00003e7e8 sp=0xc00003e7e0 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by runtime.createfing
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mfinal.go:156 +0x61
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 7 [select]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d3590, 0x0, 0x1809, 0x1)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc0000d1530 sp=0xc0000d1510 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.selectgo(0xc0000d1d00, 0xc0000d18e8, 0x10, 0x1, 0xc00014e101)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/select.go:316 +0xc73 fp=0xc0000d1658 sp=0xc0000d1530 pc=0x4488e3
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm.(*Tracer).loop(0xc000082d80)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/tracer.go:768 +0xb50 fp=0xc0000d1fd8 sp=0xc0000d1658 pc=0x7fa0c0
> [2020-02-26T13:01:22.342Z] runtime.goexit()
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000d1fe0 sp=0xc0000d1fd8 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by go.elastic.co/apm.newTracer
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/tracer.go:410 +0x82c
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 34 [GC worker (idle)]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d33c8, 0xc0000a4b20, 0x1418, 0x0)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc0004ec760 sp=0xc0004ec740 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.gcBgMarkWorker(0xc00002e000)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgc.go:1865 +0xff fp=0xc0004ec7d8 sp=0xc0004ec760 pc=0x41da0f
> [2020-02-26T13:01:22.342Z] runtime.goexit()
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0004ec7e0 sp=0xc0004ec7d8 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by runtime.gcBgMarkStartWorkers
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgc.go:1813 +0x77
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 20 [GC worker (idle)]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d33c8, 0xc0000a4b30, 0x1418, 0x0)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc000038760 sp=0xc000038740 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.gcBgMarkWorker(0xc000030800)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgc.go:1865 +0xff fp=0xc0000387d8 sp=0xc000038760 pc=0x41da0f
> [2020-02-26T13:01:22.342Z] runtime.goexit()
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000387e0 sp=0xc0000387d8 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by runtime.gcBgMarkStartWorkers
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgc.go:1813 +0x77
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 22 [GC worker (idle)]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d33c8, 0xc000026b20, 0x1418, 0x0)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc000039760 sp=0xc000039740 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.gcBgMarkWorker(0xc000035800)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgc.go:1865 +0xff fp=0xc0000397d8 sp=0xc000039760 pc=0x41da0f
> [2020-02-26T13:01:22.342Z] runtime.goexit()
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000397e0 sp=0xc0000397d8 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by runtime.gcBgMarkStartWorkers
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgc.go:1813 +0x77
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 50 [chan receive]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d3350, 0xc000098478, 0x170e, 0x2)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc000039de8 sp=0xc000039dc8 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.chanrecv(0xc000098420, 0xc000039ef8, 0xba3301, 0x7fcfb5981088)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/chan.go:525 +0x2e7 fp=0xc000039e78 sp=0xc000039de8 pc=0x4076a7
> [2020-02-26T13:01:22.342Z] runtime.chanrecv2(0xc000098420, 0xc000039ef8, 0xc0004d1500)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/chan.go:412 +0x2b fp=0xc000039ea8 sp=0xc000039e78 pc=0x4073ab
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm.(*Tracer).loop.func1(0xc000098420, 0xa72760, 0xc00008e100, 0xc0000943c0, 0xc000082d80, 0xc000096008)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/tracer.go:711 +0x1fd fp=0xc000039fb0 sp=0xc000039ea8 pc=0x80555d
> [2020-02-26T13:01:22.342Z] runtime.goexit()
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000039fb8 sp=0xc000039fb0 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by go.elastic.co/apm.(*Tracer).loop
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/tracer.go:709 +0x36f
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 72 [chan send]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d3350, 0xc000098958, 0xc00024160f, 0x2)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc0000d5900 sp=0xc0000d58e0 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.chansend(0xc000098900, 0xc0000d5a48, 0x94fc01, 0x7f7e62, 0xc00009a300)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/chan.go:236 +0x22d fp=0xc0000d5980 sp=0xc0000d5900 pc=0x406a8d
> [2020-02-26T13:01:22.342Z] runtime.chansend1(0xc000098900, 0xc0000d5a48)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/chan.go:127 +0x35 fp=0xc0000d59b8 sp=0xc0000d5980 pc=0x406855
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm.newTracer(0x9b25a6, 0xd, 0x0, 0x0, 0x0, 0x0, 0xa68300, 0xc0001b6240, 0x2540be400, 0x6fc23ac00, ...)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/tracer.go:411 +0x892 fp=0xc0000d5a68 sp=0xc0000d59b8 pc=0x7f7e62
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm.NewTracerOptions(0x9b25a6, 0xd, 0x0, 0x0, 0x0, 0x0, 0xa68300, 0xc0001b6240, 0x2540be400, 0x6fc23ac00, ...)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/tracer.go:352 +0xe4 fp=0xc0000d5b98 sp=0xc0000d5a68 pc=0x7f7594
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm/transport/transporttest.NewRecorderTracer(0xc000b10000, 0xc0000d5e20)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/transport/transporttest/recorder.go:41 +0xb0 fp=0xc0000d5ce0 sp=0xc0000d5b98 pc=0x899830
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm/module/apmrestful_test.TestContainerFilterUnknownRoute(0xc00011e7e0)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/module/apmrestful/filter_test.go:183 +0x1f3 fp=0xc0000d5f80 sp=0xc0000d5ce0 pc=0x8a4be3
> [2020-02-26T13:01:22.342Z] testing.tRunner(0xc00011e7e0, 0x9d2cb8)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/testing/testing.go:992 +0xdc fp=0xc0000d5fd0 sp=0xc0000d5f80 pc=0x502c4c
> [2020-02-26T13:01:22.342Z] runtime.goexit()
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000d5fd8 sp=0xc0000d5fd0 pc=0x467c11
> [2020-02-26T13:01:22.342Z] created by testing.(*T).Run
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/testing/testing.go:1043 +0x357
> [2020-02-26T13:01:22.342Z] 
> [2020-02-26T13:01:22.342Z] goroutine 73 [GC assist wait]:
> [2020-02-26T13:01:22.342Z] runtime.gopark(0x9d3540, 0xde81c8, 0xa52a0b, 0x2)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc00044d4c0 sp=0xc00044d4a0 pc=0x438a40
> [2020-02-26T13:01:22.342Z] runtime.goparkunlock(...)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/proc.go:310
> [2020-02-26T13:01:22.342Z] runtime.gcParkAssist(0xc00044d528)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgcmark.go:611 +0xf8 fp=0xc00044d4f0 sp=0xc00044d4c0 pc=0x41fcb8
> [2020-02-26T13:01:22.342Z] runtime.gcAssistAlloc(0xc000083080)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/mgcmark.go:475 +0x1c1 fp=0xc00044d550 sp=0xc00044d4f0 pc=0x41f6e1
> [2020-02-26T13:01:22.342Z] runtime.mallocgc(0x100000, 0x8f34c0, 0xc00044d601, 0x7ef4f9)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/malloc.go:940 +0x907 fp=0xc00044d5f0 sp=0xc00044d550 pc=0x40e367
> [2020-02-26T13:01:22.342Z] runtime.makeslice(0x8f34c0, 0x100000, 0x100000, 0xc0001b6201)
> [2020-02-26T13:01:22.342Z] 	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc00044d620 sp=0xc00044d5f0 pc=0x44d28c
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm/internal/ringbuffer.New(0x100000, 0xc0000dc210)
> [2020-02-26T13:01:22.342Z] 	/go/src/go.elastic.co/apm/internal/ringbuffer/buffer.go:57 +0x50 fp=0xc00044d658 sp=0xc00044d620 pc=0x7d6f00
> [2020-02-26T13:01:22.342Z] go.elastic.co/apm.(*Tracer).loop(0xc0001c4780)
> [2020-02-26T13:01:22.343Z] 	/go/src/go.elastic.co/apm/tracer.go:748 +0x58c fp=0xc00044dfd8 sp=0xc00044d658 pc=0x7f9afc
> [2020-02-26T13:01:22.343Z] runtime.goexit()
> [2020-02-26T13:01:22.343Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00044dfe0 sp=0xc00044dfd8 pc=0x467c11
> [2020-02-26T13:01:22.343Z] created by go.elastic.co/apm.newTracer
> [2020-02-26T13:01:22.343Z] 	/go/src/go.elastic.co/apm/tracer.go:410 +0x82c
> [2020-02-26T13:01:22.343Z] 
> [2020-02-26T13:01:22.343Z] goroutine 74 [chan receive]:
> [2020-02-26T13:01:22.343Z] runtime.gopark(0x9d3350, 0xc000098a78, 0x95170e, 0x2)
> [2020-02-26T13:01:22.343Z] 	/usr/local/go/src/runtime/proc.go:304 +0xe0 fp=0xc000b0e5e8 sp=0xc000b0e5c8 pc=0x438a40
> [2020-02-26T13:01:22.343Z] runtime.chanrecv(0xc000098a20, 0xc000b0e6f8, 0x2145001, 0x7fcfb5981088)
> [2020-02-26T13:01:22.343Z] 	/usr/local/go/src/runtime/chan.go:525 +0x2e7 fp=0xc000b0e678 sp=0xc000b0e5e8 pc=0x4076a7
> [2020-02-26T13:01:22.343Z] runtime.chanrecv2(0xc000098a20, 0xc000b0e6f8, 0xc000258000)
> [2020-02-26T13:01:22.343Z] 	/usr/local/go/src/runtime/chan.go:412 +0x2b fp=0xc000b0e6a8 sp=0xc000b0e678 pc=0x4073ab
> [2020-02-26T13:01:22.343Z] go.elastic.co/apm.(*Tracer).loop.func1(0xc000098a20, 0xa72760, 0xc000244180, 0xc00016a8a0, 0xc0001c4780, 0xc000010040)
> [2020-02-26T13:01:22.343Z] 	/go/src/go.elastic.co/apm/tracer.go:711 +0x1fd fp=0xc000b0e7b0 sp=0xc000b0e6a8 pc=0x80555d
> [2020-02-26T13:01:22.343Z] runtime.goexit()
> [2020-02-26T13:01:22.343Z] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000b0e7b8 sp=0xc000b0e7b0 pc=0x467c11
> [2020-02-26T13:01:22.343Z] created by go.elastic.co/apm.(*Tracer).loop
> [2020-02-26T13:01:22.343Z] 	/go/src/go.elastic.co/apm/tracer.go:709 +0x36f
> [2020-02-26T13:01:22.343Z] FAIL	go.elastic.co/apm/module/apmrestful	0.042s
> [2020-02-26T13:01:22.343Z] FAIL
> [2020-02-26T13:01:22.343Z] make: *** [Makefile:56: coverage] Error 1
> script returned exit code 2

**Comment by kuisathaverat** [comment]
ping us if we can help you, but sound like a StackOverflow or something like that

**Comment by axw** [comment]
I can reproduce this with Go 1.14.0, but not 1.13.8.

**Comment by axw** [comment]
https://github.com/golang/go/issues/37688
