### ISSUE TITLE
CI Test Failure: suite.go:63: test panicked: reflect: Elem of invalid type

### ISSUE THREAD

**Issue by adam-stokes** [elastic/apm-agent-go#966]
**Describe the bug**

This is a report from our automated CI testing and please let me know if this isn't the right place to file this issue. During the TestHarness suite we are receiving this stack trace:

```
22:42:14  === RUN   TestHarness
22:42:14  --- FAIL: TestHarness (0.00s)
22:42:14      suite.go:63: test panicked: reflect: Elem of invalid type
22:42:14          goroutine 51 [running]:
22:42:14          runtime/debug.Stack(0xc000038488, 0x88bde0, 0x9b3690)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/.gimme/versions/go1.11.13.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
22:42:14          github.com/stretchr/testify/suite.failOnPanic(0xc000128300)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:63 +0x60
22:42:14          panic(0x88bde0, 0x9b3690)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/.gimme/versions/go1.11.13.linux.amd64/src/runtime/panic.go:513 +0x1b9
22:42:14          reflect.(*rtype).Elem(0x933bc0, 0x9b8020, 0xc0001de000)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/.gimme/versions/go1.11.13.linux.amd64/src/reflect/type.go:923 +0x143
22:42:14          github.com/stretchr/testify/suite.Run(0xc000128300, 0x9b8020, 0xc0001de000)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:97 +0x13a
22:42:14          go.elastic.co/apm/module/apmot.TestHarness.func6(0xc0001de000)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/src/go.elastic.co/apm/module/apmot/harness_test.go:71 +0x49
22:42:14          github.com/opentracing/opentracing-go/harness.RunAPIChecks(0xc000128300, 0x953cc8, 0xc00004bf78, 0x4, 0x4)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/pkg/mod/github.com/opentracing/opentracing-go@v1.1.0/harness/api_checkers.go:70 +0x68
22:42:14          go.elastic.co/apm/module/apmot.TestHarness(0xc000128300)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/src/go.elastic.co/apm/module/apmot/harness_test.go:66 +0x175
22:42:14          testing.tRunner(0xc000128300, 0x953cd8)
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/.gimme/versions/go1.11.13.linux.amd64/src/testing/testing.go:827 +0xbf
22:42:14          created by testing.(*T).Run
22:42:14          	/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/.gimme/versions/go1.11.13.linux.amd64/src/testing/testing.go:878 +0x35c
```

This is on the amd64 platform utilizing go version 1.11.13. The full link to the failed job is: https://apm-ci.elastic.co/job/apm-agent-go/job/apm-agent-go-mbp/job/master/242/consoleFull

**To Reproduce**
1.  We can reproduce this by re-running the pipeline job which seems to run `make test`

**Expected behavior**

I believe we are still supporting Go version 1.11.x for the go agent so all tests for that version should pass

**Comment by axw** [comment]
Thanks @adam-stokes! This was broken in https://github.com/elastic/apm-agent-go/pull/960, and subsequently fixed by https://github.com/elastic/apm-agent-go/pull/964. The latest CI run is green: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/master/245/pipeline. I think we're good so I'll close; please reopen if I missed something.
